import type { Metadata } from 'next';
import { publicSans } from './ui/fonts';
import './sass/style.scss';

export const metadata: Metadata = {
  title: 'Personal Finance App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${publicSans.className}`}>
      <body>{children}</body>
    </html>
  );
}
